Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2019
Var
quantidade: inteiro
total:real

Inicio
escreva("informe a quantidade de folhas:")
leia(quantidade)
 se quantidade <= 100 entao
     total <- quantidade * 0.25
 senao
     total <- quantidade * 0.20
 fimse
 escreva("o valor a pagar e:",total," Reais")


Fimalgoritmo